### ISSUE TITLE
Previews of Blacy Emoticons not showing up

### ISSUE THREAD

**Issue by DursunCanPoyraz** [the-turk/flarum-flamoji#1]
![image](https://user-images.githubusercontent.com/74768208/125198864-609a4380-e26c-11eb-8733-da8db620f2d1.png)

![image](https://user-images.githubusercontent.com/74768208/125198875-698b1500-e26c-11eb-9a16-72d5596ecea2.png)

**Comment by the-turk** [comment]
görselleri nereye attın?

**Comment by DursunCanPoyraz** [comment]
> görselleri nereye attın?

/assets/emojis/blacy

**Comment by the-turk** [comment]
Bende bir sorun görünmüyor 

![](https://i.imgur.com/tRH0EnV.png)

**Comment by DursunCanPoyraz** [comment]
İlk başta yanlış klasöre yüklemiştim. Sonra klasörü düzelttim. Önbellek ile alakalı bir sorundu galiba. Bende de düzelmiş.

![image](https://user-images.githubusercontent.com/74768208/125349245-fb2a7d80-e365-11eb-871c-7a56f9f05a9b.png)
